### PR TITLE
added requested feature to query allHehes. Resolved linting error fro…

### PR DESCRIPTION
**Pull request by Muncherkin**
…m post.api.test.ts. 

Issue #241: Nu finns en query, `allHehes` (med optional `sortOrder`), för att hämta alla hehes. All funktionalitet fanns redan så inga nya tester eller så, bara en rad till i graph:en och resolvern (`hehe.graphql` och `hehe.resolver.ts`).

### CODE REVIEW

**Comment by ginger51011** [comment]
Är inte detta samma sak som `latestHehes`, där limit är `null`?

**Comment by Muncherkin** [comment]
> Är inte detta samma sak som `latestHehes`, där limit är `null`?

Jo men Froborg tyckte det var fult. Låg kvar som en "issue" så jag la till det.

**Review by ginger51011 — APPROVED** [review]
LGTM

(Men lägg gärna till dig i contributors i package.json om du inte är där)

**Review by afroborg — CHANGES_REQUESTED** [review]
Before we merge this we really should start looking into paginating our `all-x`-reponses. This is not an issue now, but once we start having a few months of stuff it's really gonna impact load time.

I suggest we add some more fields:
- `page_size` / `limit`: the max number of items returned
- `page`: the page we want

The response is going to be more complex, because we need to return information about `nextPage`, `totalCount` etc. @blennster has done this in the past on other projects.

**Comment by afroborg** [comment]
Also - with this resolver I don't really see the need for the `latestHehes` resolver anymore. Removing it won't break anything that I know of, don't think we use it anywhere.

**Comment by Muncherkin** [comment]
I'd be happy to remove the `latestHehe` query. I'll look into the paging thing. Feels a bit like where solving a non-issue though just cause we weren't a fan of the label `latest` lol

**Comment by Muncherkin** [comment]
Same thing as `latestHehes(null)`, closing PR.

**Pull request closed without merging**
